# Site settings
title: dogfooter [개-발자]
description: > # this means to ignore newlines until "baseurl:"
    dogfooter는 dog의 '개'와 foot의 '발'을 합쳐 dogfoot의 '개발'이란 단어를 만들고 뒤에 er을 붙여 '~하는 사람'이라 하여 개발하는 사람 즉 개발자라는 의미를 갖게되었습니다.
    열심히 공부하는 작은 학부생입니다.
url: "https://dogfooter.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: 

# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Ju Hyeonsu'
  email: dogfooter219@gmail.com
  twitter_username: dogfooter219
  facebook_username: 주현수
  github_username:  dogfooter



google_analytics: UA-91398386-1
disqus: 
    shortname: https-dogfooter-github-io

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
